export const GET_ALL_VEHICLES = 'GET_ALL_VEHICLES';
export const GET_ALL_VEHICLES_SUCCES = 'GET_ALL_VEHICLES_SUCCESS';

export const VEHICLE_DETAIL = 'VEHICLE_DETAIL';

export const BOOK_VEHICLE = 'BOOK_VEHICLE';

export const ESTIMATE_VEHICLE = 'ESTIMATE_VEHICLE';
